/* ─────────────────────────────────────────────────────────
 * FORMIC CONFIG — the defaults an app chose, read by components
 *
 * Generated by scripts/apply_config.py from formic.config.json.
 * Edit the json (or paste a block from formicai.dev/customize)
 * and run the script; do not edit this file by hand.
 *
 * Only the choices that are prop defaults live here. Colour,
 * palette, radius, size and theme are tokens and <html> data
 * attributes, which the same script writes.
 * ───────────────────────────────────────────────────────── */
export type FormicConfig = {
  /** people without a photo: initials in an ink circle, or a drawn face (DiceBear notionists) */
  avatar: "initials" | "doodle";
  /** AppSidebar's starting variant */
  sidebar: "expanded" | "rail";
  /** charts and sparklines animate in (reduced-motion still wins) */
  motion: boolean;
};

export const FORMIC_CONFIG: FormicConfig = {
  avatar: "initials",
  sidebar: "expanded",
  motion: true,
};
